import popcounter from "./popcounter";
const kotty = [
  {
    id: 'kot1',
    image: "./Images/kot1.jpg",
    likes: 5,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  { 
    id: 'kot2',
    image: "./Images/kot2.jpg",
    likes: 6,
    dislikes: 1,
    popularity: popcounter,
    favourite: true,
  },
  {
    id: 'kot3',
    image: "./Images/kot3.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  {
    id: 'kot4',
    image: "./Images/kot4.jpg",
    likes: 10,
    dislikes: 0,
    popularity: popcounter,
    favourite: true,
  },
  {
    id: 'kot5',
    image: "./Images/kot5.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  {
    id: 'kot6',
    image: "./Images/kot6.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  {
  id: 'kot7',
    image: "./Images/kot7.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  {
    id: 'kot8',
    image: "./Images/kot8.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  {
    id: 'kot9',
    image: "./Images/kot9.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
  {
    id: 'kot10',
    image: "./Images/kot10.jpg",
    likes: 0,
    dislikes: 0,
    popularity: popcounter,
    favourite: false,
  },
];

export default kotty;
